name: Prettier code formatter
on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Prettier 💾
        run: npm install --save-dev --save-exact prettier @shopify/prettier-plugin-liquid
      - name: Auto-format ✨
        run: npx prettier . --write
      - name: Commit formatting fixes 📌
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format with Prettier"
